const fs = require('fs');
const p = 'D:/DS Project/distributed_movie_booking_system/frontend/src/pages/AdminDashboard.js';

const lines = [];
const a = (s) => lines.push(s);

a("import React, { useEffect, useState, useCallback, useRef } from 'react';");
a("import Navbar from '../components/Navbar';");
a("import API from '../api';");
a("import { useNavigate } from 'react-router-dom';");
a("import { io } from 'socket.io-client';");
a("");
a("const socket = io('http://localhost:5000');");
a("const TABS = ['Overview','Analytics','Live Feed','Movies','Shows','Theatres','Bookings'];");
a("");
a("function AdminDashboard() {");
a("  const navigate = useNavigate();");
a("  const [activeTab, setActiveTab] = useState('Overview');");
a("  const [movies, setMovies] = useState([]);");
a("  const [shows, setShows] = useState([]);");
a("  const [theatres, setTheatres] = useState([]);");
a("  const [bookings, setBookings] = useState([]);");
a("  const [analytics, setAnalytics] = useState(null);");
a("  const [liveActivity, setLiveActivity] = useState([]);");
a("  const [loading, setLoading] = useState(false);");
a("  const feedRef = useRef(null);");
a("");
a("  const fetchData = useCallback(async () => {");
a("    setLoading(true);");
a("    try {");
a("      const [moviesRes, showsRes, theatresRes, bookingsRes] = await Promise.all([");
a("        API.get('/movies'), API.get('/admin/shows'), API.get('/admin/theatres'), API.get('/bookings')");
a("      ]);");
a("      setMovies(moviesRes.data); setShows(showsRes.data);");
a("      setTheatres(theatresRes.data); setBookings(bookingsRes.data);");
a("    } catch(e){console.log(e);} finally{setLoading(false);}");
a("  }, []);");
a("");
a("  const fetchAnalytics = useCallback(async () => {");
a("    try { const res = await API.get('/analytics'); setAnalytics(res.data); } catch(e){console.log(e);}");
a("  }, []);");
a("");
a("  useEffect(() => {");
a("    fetchData(); fetchAnalytics();");
a("    socket.emit('joinAdmin');");
a("    socket.on('newBookingActivity', (data) => { setLiveActivity(prev => [data,...prev].slice(0,50)); });");
a("    return () => { socket.emit('leaveAdmin'); socket.off('newBookingActivity'); };");
a("  }, [fetchData, fetchAnalytics]);");
a("");
a("  const deleteMovie = async (id) => {");
a("    if (!window.confirm('Delete this movie?')) return;");
a("    try { await API.delete('/movies/'+id); setMovies(p=>p.filter(m=>m._id!==id)); } catch(e){alert('Failed');}");
a("  };");
a("  const deleteShow = async (id) => {");
a("    if (!window.confirm('Delete this show?')) return;");
a("    try { await API.delete('/admin/show/'+id); setShows(p=>p.filter(s=>s._id!==id)); } catch(e){alert('Failed');}");
a("  };");
a("  const deleteTheatre = async (id) => {");
a("    if (!window.confirm('Delete this theatre?')) return;");
a("    try { await API.delete('/admin/theatre/'+id); setTheatres(p=>p.filter(t=>t._id!==id)); } catch(e){alert('Failed');}");
a("  };");
a("");
a("  const totalRevenue = bookings.filter(b=>b.status!=='CANCELLED').reduce((s,b)=>s+(b.totalAmount||0),0);");
a("  const confirmedBookings = bookings.filter(b=>b.status!=='CANCELLED');");
a("  const cancelledBookings = bookings.filter(b=>b.status==='CANCELLED');");
a("");
a("  return (");
a("    <>");
a("      <Navbar />");
a("      <div style={{background:'#0a0f1e',minHeight:'100vh',color:'white',padding:'30px'}}>");
a("");
a("        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'30px'}}>");
a("          <div>");
a("            <h1 style={{color:'#ff004f',fontSize:'32px',margin:0,fontWeight:'900'}}>Admin Dashboard</h1>");
a("            <p style={{color:'#64748b',margin:'5px 0 0',fontSize:'14px'}}>CineVerse Management Panel</p>");
a("          </div>");
a("          <button onClick={()=>{fetchData();fetchAnalytics();}} style={refreshBtnStyle} disabled={loading}>");
a("            {loading ? 'Refreshing...' : 'Refresh'}");
a("          </button>");
a("        </div>");
a("");
a("        <div style={{display:'flex',gap:'8px',marginBottom:'30px',flexWrap:'wrap'}}>");
a("          {TABS.map(tab => (");
a("            <button key={tab} onClick={()=>setActiveTab(tab)} style={{padding:'9px 18px',borderRadius:'10px',border:activeTab===tab?'none':'1px solid rgba(255,255,255,0.06)',cursor:'pointer',fontWeight:'700',fontSize:'13px',background:activeTab===tab?'#ff004f':'#111827',color:activeTab===tab?'white':'#94a3b8',position:'relative'}}>");
a("              {tab}");
a("              {tab==='Live Feed' && liveActivity.length>0 && <span style={{position:'absolute',top:'-6px',right:'-6px',background:'#10b981',borderRadius:'50%',width:'16px',height:'16px',fontSize:'9px',display:'flex',alignItems:'center',justifyContent:'center',color:'white'}}>{liveActivity.length>9?'9+':liveActivity.length}</span>}");
a("            </button>");
a("          ))}");
a("        </div>");

a("        {activeTab==='Overview' && (");
a("          <div>");
a("            <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(200px,1fr))',gap:'20px',marginBottom:'40px'}}>");
a("              <StatCard label='Total Movies' value={movies.length} icon='🎬' color='#6366f1' />");
a("              <StatCard label='Total Shows' value={shows.length} icon='🎭' color='#0ea5e9' />");
a("              <StatCard label='Total Theatres' value={theatres.length} icon='🏛️' color='#10b981' />");
a("              <StatCard label='Confirmed Bookings' value={confirmedBookings.length} icon='🎟️' color='#f59e0b' />");
a("              <StatCard label='Cancelled' value={cancelledBookings.length} icon='✕' color='#ef4444' />");
a("              <StatCard label='Total Revenue' value={'₹'+totalRevenue.toLocaleString()} icon='💰' color='#ff004f' />");
a("            </div>");
a("            <h2 style={{marginBottom:'15px',fontWeight:'800'}}>Quick Actions</h2>");
a("            <div style={{display:'flex',gap:'12px',flexWrap:'wrap'}}>");
a("              <ActionBtn label='Add Movie' onClick={()=>navigate('/admin/add-movie')} />");
a("              <ActionBtn label='Add Show' onClick={()=>navigate('/admin/add-show')} />");
a("              <ActionBtn label='Add Theatre' onClick={()=>navigate('/admin/add-theatre')} />");
a("              <ActionBtn label='Analytics' onClick={()=>setActiveTab('Analytics')} secondary />");
a("              <ActionBtn label='Live Feed' onClick={()=>setActiveTab('Live Feed')} secondary />");
a("            </div>");
a("          </div>");
a("        )}");
a("");
a("        {activeTab==='Analytics' && (");
a("          <div>");
a("            {!analytics ? <div style={{textAlign:'center',padding:'60px',color:'#94a3b8'}}><p>Loading analytics...</p></div> : (");
a("              <div style={{display:'flex',flexDirection:'column',gap:'30px'}}>");
a("                <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:'16px'}}>");
a("                  <StatCard label='Total Revenue' value={'₹'+(analytics.summary?.totalRevenue||0).toLocaleString()} icon='💰' color='#10b981' />");
a("                  <StatCard label='Tickets Sold' value={analytics.summary?.totalTickets||0} icon='🎟️' color='#6366f1' />");
a("                  <StatCard label='Bookings' value={analytics.summary?.totalBookings||0} icon='📋' color='#0ea5e9' />");
a("                  <StatCard label='Cancelled' value={analytics.summary?.cancelledBookings||0} icon='✕' color='#ef4444' />");
a("                </div>");
a("                <ChartCard title='Bookings Per Movie' subtitle='Tickets sold per movie'>");
a("                  {(analytics.bookingsPerMovie||[]).length===0 ? <p style={{color:'#334155',textAlign:'center',padding:'20px'}}>No data yet</p> : (analytics.bookingsPerMovie||[]).map((item,i)=>{");
a("                    const max=(analytics.bookingsPerMovie[0]?.count)||1;");
a("                    const pct=Math.round((item.count/max)*100);");
a("                    const colors=['#ff004f','#6366f1','#0ea5e9','#10b981','#f59e0b','#ec4899','#8b5cf6','#14b8a6'];");
a("                    return (<div key={i} style={{marginBottom:'14px'}}>");
a("                      <div style={{display:'flex',justifyContent:'space-between',marginBottom:'6px'}}>");
a("                        <span style={{color:'white',fontSize:'13px',fontWeight:'600'}}>{item.movie}</span>");
a("                        <span style={{color:'#94a3b8',fontSize:'13px'}}>{item.count} tickets</span>");
a("                      </div>");
a("                      <div style={{height:'10px',background:'#1e293b',borderRadius:'5px',overflow:'hidden'}}>");
a("                        <div style={{height:'100%',width:pct+'%',background:colors[i%colors.length],borderRadius:'5px'}} />");
a("                      </div>");
a("                    </div>);");
a("                  })}");
a("                </ChartCard>");
a("                <ChartCard title='Revenue Per Theatre' subtitle='Total revenue per theatre'>");
a("                  {(analytics.revenuePerTheatre||[]).length===0 ? <p style={{color:'#334155',textAlign:'center',padding:'20px'}}>No data yet</p> : (analytics.revenuePerTheatre||[]).map((item,i)=>{");
a("                    const max=(analytics.revenuePerTheatre[0]?.revenue)||1;");
a("                    const pct=Math.round((item.revenue/max)*100);");
a("                    const colors=['#10b981','#0ea5e9','#6366f1','#f59e0b','#ff004f'];");
a("                    return (<div key={i} style={{marginBottom:'14px'}}>");
a("                      <div style={{display:'flex',justifyContent:'space-between',marginBottom:'6px'}}>");
a("                        <span style={{color:'white',fontSize:'13px',fontWeight:'600'}}>{item.theatre}</span>");
a("                        <span style={{color:'#10b981',fontSize:'13px',fontWeight:'700'}}>{'₹'+item.revenue?.toLocaleString()}</span>");
a("                      </div>");
a("                      <div style={{height:'10px',background:'#1e293b',borderRadius:'5px',overflow:'hidden'}}>");
a("                        <div style={{height:'100%',width:pct+'%',background:colors[i%colors.length],borderRadius:'5px'}} />");
a("                      </div>");
a("                    </div>);");
a("                  })}");
a("                </ChartCard>");
a("                <ChartCard title='Occupancy Rate' subtitle='Seat fill % per show'>");
a("                  {(analytics.occupancy||[]).length===0 ? <p style={{color:'#334155',textAlign:'center',padding:'20px'}}>No data yet</p> : (analytics.occupancy||[]).map((item,i)=>{");
a("                    const color=item.rate>80?'#ef4444':item.rate>50?'#f59e0b':'#10b981';");
a("                    return (<div key={i} style={{marginBottom:'14px'}}>");
a("                      <div style={{display:'flex',justifyContent:'space-between',marginBottom:'6px'}}>");
a("                        <span style={{color:'white',fontSize:'12px',fontWeight:'600',flex:1,marginRight:'12px'}}>{item.label}</span>");
a("                        <span style={{color:color,fontSize:'13px',fontWeight:'700'}}>{item.rate}%</span>");
a("                      </div>");
a("                      <div style={{height:'10px',background:'#1e293b',borderRadius:'5px',overflow:'hidden'}}>");
a("                        <div style={{height:'100%',width:item.rate+'%',background:color,borderRadius:'5px'}} />");
a("                      </div>");
a("                    </div>);");
a("                  })}");
a("                </ChartCard>");
a("                <ChartCard title='Peak Booking Hours' subtitle='Bookings by hour of day'>");
a("                  <div style={{display:'flex',alignItems:'flex-end',gap:'4px',height:'120px'}}>");
a("                    {(analytics.peakHours||[]).map((item,i)=>{");
a("                      const max=Math.max(...(analytics.peakHours||[]).map(h=>h.count),1);");
a("                      const h=Math.max((item.count/max)*100,4);");
a("                      return (<div key={i} style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',gap:'4px'}} title={item.hour+': '+item.count+' bookings'}>");
a("                        <div style={{width:'100%',height:h+'%',background:item.count>0?'#ff004f':'#1e293b',borderRadius:'3px 3px 0 0',minHeight:'4px'}} />");
a("                        {i%4===0 && <span style={{color:'#334155',fontSize:'9px'}}>{i}</span>}");
a("                      </div>);");
a("                    })}");
a("                  </div>");
a("                  <div style={{display:'flex',justifyContent:'space-between',marginTop:'8px'}}>");
a("                    <span style={{color:'#64748b',fontSize:'11px'}}>12 AM</span>");
a("                    <span style={{color:'#64748b',fontSize:'11px'}}>12 PM</span>");
a("                    <span style={{color:'#64748b',fontSize:'11px'}}>11 PM</span>");
a("                  </div>");
a("                </ChartCard>");
a("              </div>");
a("            )}");
a("          </div>");
a("        )}");

a("        {activeTab==='Live Feed' && (");
a("          <div>");
a("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'20px'}}>");
a("              <div>");
a("                <h2 style={{margin:0,fontWeight:'800'}}>Live Booking Activity</h2>");
a("                <p style={{color:'#64748b',margin:'4px 0 0',fontSize:'13px'}}>Real-time feed via Socket.IO</p>");
a("              </div>");
a("              <div style={{display:'flex',alignItems:'center',gap:'8px'}}>");
a("                <div style={{width:'8px',height:'8px',borderRadius:'50%',background:'#10b981',boxShadow:'0 0 8px #10b981'}} />");
a("                <span style={{color:'#10b981',fontSize:'13px',fontWeight:'700'}}>LIVE</span>");
a("                {liveActivity.length>0 && <button onClick={()=>setLiveActivity([])} style={{padding:'6px 12px',background:'rgba(239,68,68,0.1)',border:'1px solid rgba(239,68,68,0.3)',borderRadius:'8px',color:'#ef4444',cursor:'pointer',fontSize:'12px',fontWeight:'600'}}>Clear</button>}");
a("              </div>");
a("            </div>");
a("            {liveActivity.length===0 ? (");
a("              <div style={{background:'#111827',borderRadius:'20px',padding:'60px',textAlign:'center',border:'1px solid rgba(255,255,255,0.06)'}}>");
a("                <div style={{fontSize:'56px',marginBottom:'16px'}}>📡</div>");
a("                <h3 style={{color:'#94a3b8',fontWeight:'700'}}>Waiting for activity...</h3>");
a("                <p style={{color:'#64748b',fontSize:'14px'}}>Bookings and cancellations will appear here in real-time</p>");
a("              </div>");
a("            ) : (");
a("              <div ref={feedRef} style={{display:'flex',flexDirection:'column',gap:'10px',maxHeight:'600px',overflowY:'auto'}}>");
a("                {liveActivity.map((item,i) => (");
a("                  <div key={i} style={{background:'#111827',borderRadius:'14px',padding:'16px 20px',border:'1px solid '+(item.type==='CANCELLATION'?'rgba(239,68,68,0.2)':'rgba(16,185,129,0.2)'),display:'flex',alignItems:'center',gap:'16px'}}>");
a("                    <div style={{width:'44px',height:'44px',borderRadius:'12px',background:item.type==='CANCELLATION'?'rgba(239,68,68,0.15)':'rgba(16,185,129,0.15)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'20px',flexShrink:0}}>");
a("                      {item.type==='CANCELLATION'?'✕':'🎟️'}");
a("                    </div>");
a("                    <div style={{flex:1}}>");
a("                      <p style={{margin:0,color:'white',fontSize:'14px',fontWeight:'700'}}>");
a("                        <span style={{color:item.type==='CANCELLATION'?'#ef4444':'#10b981'}}>{item.userName}</span>");
a("                        {item.type==='CANCELLATION'?' cancelled ':' booked '}");
a("                        <span style={{color:'#fbbf24'}}>{(item.seats||[]).join(', ')}</span>");
a("                        {' for '}");
a("                        <span style={{color:'#818cf8'}}>{item.movieTitle}</span>");
a("                        {item.theatreName && <span style={{color:'#64748b'}}> @ {item.theatreName}</span>}");
a("                      </p>");
a("                    </div>");
a("                    <span style={{color:'#334155',fontSize:'11px',whiteSpace:'nowrap',flexShrink:0}}>");
a("                      {new Date(item.timestamp).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}");
a("                    </span>");
a("                  </div>");
a("                ))}");
a("              </div>");
a("            )}");
a("          </div>");
a("        )}");
a("");
a("        {activeTab==='Movies' && (");
a("          <div>");
a("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'20px'}}>");
a("              <h2 style={{margin:0}}>Movies ({movies.length})</h2>");
a("              <button onClick={()=>navigate('/admin/add-movie')} style={addBtnStyle}>Add Movie</button>");
a("            </div>");
a("            {movies.length===0 ? <EmptyState message='No movies added yet.' /> : (");
a("              <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))',gap:'20px'}}>");
a("                {movies.map(movie => (");
a("                  <div key={movie._id} style={cardStyle}>");
a("                    <img src={movie.poster||'https://via.placeholder.com/300x200?text=No+Poster'} alt={movie.title} style={{width:'100%',height:'180px',objectFit:'cover',borderRadius:'10px',marginBottom:'12px'}} />");
a("                    <h3 style={{margin:'0 0 6px',color:'white'}}>{movie.title}</h3>");
a("                    <p style={{color:'#94a3b8',margin:'3px 0',fontSize:'13px'}}>{movie.genre} | {movie.language}</p>");
a("                    <p style={{color:'#94a3b8',margin:'3px 0',fontSize:'13px'}}>Rating: {movie.rating} | {movie.duration}</p>");
a("                    <div style={{display:'flex',gap:'10px',marginTop:'14px'}}>");
a("                      <button onClick={()=>navigate('/admin/edit-movie/'+movie._id)} style={editBtnStyle}>Edit</button>");
a("                      <button onClick={()=>deleteMovie(movie._id)} style={deleteBtnStyle}>Delete</button>");
a("                    </div>");
a("                  </div>");
a("                ))}");
a("              </div>");
a("            )}");
a("          </div>");
a("        )}");
a("");
a("        {activeTab==='Shows' && (");
a("          <div>");
a("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'20px'}}>");
a("              <h2 style={{margin:0}}>Shows ({shows.length})</h2>");
a("              <button onClick={()=>navigate('/admin/add-show')} style={addBtnStyle}>Add Show</button>");
a("            </div>");
a("            {shows.length===0 ? <EmptyState message='No shows added yet.' /> : (");
a("              <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'20px'}}>");
a("                {shows.map(show => {");
a("                  const booked=show.bookedSeats?.length||0; const total=show.seats?.length||50;");
a("                  const pct=Math.round((booked/total)*100);");
a("                  return (<div key={show._id} style={cardStyle}>");
a("                    <h3 style={{margin:'0 0 8px',color:'#ff004f'}}>{show.movie?.title||'Unknown'}</h3>");
a("                    <p style={{color:'#94a3b8',margin:'4px 0',fontSize:'13px'}}>{show.theatre?.name}</p>");
a("                    <p style={{color:'#94a3b8',margin:'4px 0',fontSize:'13px'}}>{show.showTime}</p>");
a("                    <p style={{color:'#94a3b8',margin:'4px 0',fontSize:'13px'}}>Price: Rs.{show.price}</p>");
a("                    <div style={{margin:'10px 0 4px',display:'flex',justifyContent:'space-between'}}>");
a("                      <span style={{color:'#64748b',fontSize:'12px'}}>Occupancy</span>");
a("                      <span style={{color:pct>80?'#ef4444':'#10b981',fontSize:'12px',fontWeight:'700'}}>{booked}/{total} ({pct}%)</span>");
a("                    </div>");
a("                    <div style={{height:'6px',background:'#0a0f1e',borderRadius:'3px',overflow:'hidden'}}>");
a("                      <div style={{height:'100%',width:pct+'%',background:pct>80?'#ef4444':pct>50?'#f59e0b':'#10b981',borderRadius:'3px'}} />");
a("                    </div>");
a("                    <button onClick={()=>deleteShow(show._id)} style={{...deleteBtnStyle,width:'100%',marginTop:'14px'}}>Delete Show</button>");
a("                  </div>);");
a("                })}");
a("              </div>");
a("            )}");
a("          </div>");
a("        )}");
a("");
a("        {activeTab==='Theatres' && (");
a("          <div>");
a("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'20px'}}>");
a("              <h2 style={{margin:0}}>Theatres ({theatres.length})</h2>");
a("              <button onClick={()=>navigate('/admin/add-theatre')} style={addBtnStyle}>Add Theatre</button>");
a("            </div>");
a("            {theatres.length===0 ? <EmptyState message='No theatres added yet.' /> : (");
a("              <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:'20px'}}>");
a("                {theatres.map(theatre => (");
a("                  <div key={theatre._id} style={cardStyle}>");
a("                    <h3 style={{margin:'0 0 8px',color:'white'}}>{theatre.name}</h3>");
a("                    <p style={{color:'#94a3b8',margin:'4px 0',fontSize:'13px'}}>{theatre.city}</p>");
a("                    <p style={{color:'#94a3b8',margin:'4px 0',fontSize:'13px'}}>{theatre.screens} Screen(s)</p>");
a("                    <button onClick={()=>deleteTheatre(theatre._id)} style={{...deleteBtnStyle,width:'100%',marginTop:'14px'}}>Delete Theatre</button>");
a("                  </div>");
a("                ))}");
a("              </div>");
a("            )}");
a("          </div>");
a("        )}");
a("");
a("        {activeTab==='Bookings' && (");
a("          <div>");
a("            <h2 style={{marginBottom:'20px'}}>All Bookings ({bookings.length})</h2>");
a("            {bookings.length===0 ? <EmptyState message='No bookings yet.' /> : (");
a("              <div style={{overflowX:'auto'}}>");
a("                <table style={{width:'100%',borderCollapse:'collapse',fontSize:'14px'}}>");
a("                  <thead>");
a("                    <tr style={{background:'#111827',color:'#94a3b8'}}>");
a("                      {['Booking ID','User','Movie','Theatre','Seats','Amount','Status'].map(h=>(");
a("                        <th key={h} style={{padding:'12px 16px',textAlign:'left',fontWeight:'600',borderBottom:'1px solid rgba(255,255,255,0.06)'}}>{h}</th>");
a("                      ))}");
a("                    </tr>");
a("                  </thead>");
a("                  <tbody>");
a("                    {bookings.map(b=>(");
a("                      <tr key={b._id} style={{borderBottom:'1px solid rgba(255,255,255,0.04)'}}>");
a("                        <td style={tdStyle}><span style={{fontFamily:'monospace',fontSize:'12px',color:'#64748b'}}>{(b.bookingId||'').slice(0,8)}...</span></td>");
a("                        <td style={tdStyle}>{b.user?.name||'—'}</td>");
a("                        <td style={tdStyle}>{b.movie?.title||'—'}</td>");
a("                        <td style={tdStyle}>{b.theatre?.name||'—'}</td>");
a("                        <td style={tdStyle}>{(b.seats||[]).join(', ')}</td>");
a("                        <td style={tdStyle}><span style={{color:'#10b981',fontWeight:'700'}}>Rs.{b.totalAmount}</span></td>");
a("                        <td style={tdStyle}><span style={{background:b.status==='CANCELLED'?'rgba(239,68,68,0.15)':'rgba(16,185,129,0.15)',border:'1px solid '+(b.status==='CANCELLED'?'rgba(239,68,68,0.4)':'rgba(16,185,129,0.4)'),color:b.status==='CANCELLED'?'#ef4444':'#10b981',padding:'3px 10px',borderRadius:'20px',fontSize:'11px',fontWeight:'700'}}>{b.status||'CONFIRMED'}</span></td>");
a("                      </tr>");
a("                    ))}");
a("                  </tbody>");
a("                </table>");
a("              </div>");
a("            )}");
a("          </div>");
a("        )}");
a("");
a("      </div>");
a("    </>");
a("  );");
a("}");
a("");
a("function StatCard({label,value,icon,color}) {");
a("  return (<div style={{background:'#111827',padding:'24px',borderRadius:'16px',borderLeft:'4px solid '+color,border:'1px solid rgba(255,255,255,0.06)',borderLeftWidth:'4px',borderLeftColor:color}}>");
a("    <span style={{fontSize:'28px'}}>{icon}</span>");
a("    <p style={{color:'#64748b',fontSize:'12px',margin:'8px 0 4px',fontWeight:'600',textTransform:'uppercase',letterSpacing:'1px'}}>{label}</p>");
a("    <p style={{fontSize:'26px',fontWeight:'900',color:'white',margin:0}}>{value}</p>");
a("  </div>);");
a("}");
a("");
a("function ChartCard({title,subtitle,children}) {");
a("  return (<div style={{background:'#111827',borderRadius:'20px',padding:'28px',border:'1px solid rgba(255,255,255,0.06)'}}>");
a("    <h3 style={{margin:'0 0 4px',fontSize:'18px',fontWeight:'800',color:'white'}}>{title}</h3>");
a("    <p style={{color:'#64748b',fontSize:'13px',margin:'0 0 24px'}}>{subtitle}</p>");
a("    {children}");
a("  </div>);");
a("}");
a("");
a("function ActionBtn({label,onClick,secondary}) {");
a("  return (<button onClick={onClick} style={{padding:'12px 20px',background:secondary?'#111827':'#ff004f',border:secondary?'1px solid rgba(255,255,255,0.08)':'none',borderRadius:'10px',color:secondary?'#94a3b8':'white',fontSize:'14px',cursor:'pointer',fontWeight:'700'}}>{label}</button>);");
a("}");
a("");
a("function EmptyState({message}) {");
a("  return (<div style={{background:'#111827',padding:'40px',borderRadius:'16px',textAlign:'center',color:'#64748b',border:'1px solid rgba(255,255,255,0.06)'}}><p style={{fontSize:'18px'}}>{message}</p></div>);");
a("}");
a("");
a("const cardStyle={background:'#111827',padding:'20px',borderRadius:'16px',border:'1px solid rgba(255,255,255,0.06)'};");
a("const addBtnStyle={padding:'10px 20px',background:'#ff004f',border:'none',borderRadius:'10px',color:'white',cursor:'pointer',fontWeight:'700',fontSize:'14px'};");
a("const editBtnStyle={flex:1,padding:'8px',background:'rgba(14,165,233,0.15)',border:'1px solid rgba(14,165,233,0.3)',borderRadius:'8px',color:'#0ea5e9',cursor:'pointer',fontWeight:'700',fontSize:'13px'};");
a("const deleteBtnStyle={flex:1,padding:'8px',background:'rgba(239,68,68,0.1)',border:'1px solid rgba(239,68,68,0.3)',borderRadius:'8px',color:'#ef4444',cursor:'pointer',fontWeight:'700',fontSize:'13px'};");
a("const refreshBtnStyle={padding:'10px 20px',background:'#111827',border:'1px solid rgba(255,255,255,0.08)',borderRadius:'10px',color:'white',cursor:'pointer',fontWeight:'700',fontSize:'14px'};");
a("const tdStyle={padding:'12px 16px',color:'white'};");
a("");
a("export default AdminDashboard;");

fs.writeFileSync(p, lines.join('\n'), 'utf8');
console.log('DONE! Lines:', lines.length, 'Bytes:', fs.statSync(p).size);
